title: HiveMQ MQTT Client
description: A fast, asynchronous, reactive mqtt client library
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
logo: assets/img/MQTT Bee Logo.svg

search_enabled: true

color_scheme: dark

aux_links:
  "News":
    - "hivemq-mqtt-client/news"
  "HiveMQ MQTT Client on GitHub":
    - "https://github.com/hivemq/hivemq-mqtt-client"

plugins:
  - jekyll-relative-links