title: MQTT Bee
description: A fast, asynchronous, reactive mqtt client library
theme: just-the-docs
#remote_theme: pmarsceill/just-the-docs
logo: assets/img/MQTT Bee Logo.svg

search_enabled: true

color_scheme: dark

aux_links:
  "News":
    - "/news"
  "MQTT Bee on GitHub":
    - "https://github.com/mqtt-bee/mqtt-bee"

plugins:
  - jekyll-relative-links