title: HiveMQ MQTT Client
description: A fast, asynchronous, reactive mqtt client library

remote_theme: pmarsceill/just-the-docs@v0.2.3

logo: assets/img/hivemq-mqtt-client-banner-neg.svg

search_enabled: true

color_scheme: dark

aux_links:
  "News":
    - "https://hivemq.github.io/hivemq-mqtt-client/news"
  "GitHub":
    - "https://github.com/hivemq/hivemq-mqtt-client"

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

github: [metadata]